name: Bad-Template-Name

on:
  workflow_dispatch:

env:
  description: This workflow will not be able to be submitted because the name of the file has more than one '-' in it.

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      outputA: 'hello'
      outputB: 'goodbye'

    steps:
      - name: print
        run: echo "Whooo Hoo! We made it!!!! I'm no longer a failing workflow!!"
