name: Various input tests

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Target repository for operaiton
        type: string
        required: true
      someValue:
        description: An identifer (with a regex of ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$)
        type: string
        required: true
      someOtherValue:
        description: Another identifier (that is a a GUID or UUID)
        type: string
        required: false

env:
  description: This workflow is used to test entity inputs that resolve to entity references.

jobs:
  talk:
    runs-on: ubuntu-latest

    steps:
      - run: echo "### Repository ${{ inputs.ref_repository }}! :rocket:" >> $GITHUB_STEP_SUMMARY
      - run: echo "### Some Value ${{ inputs.some_value }}! :rocket:" >> $GITHUB_STEP_SUMMARY
