name: Empty

# permissions:
#   id-token: write
#   contents: read

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

  push:
    branches:
      - master
      - "dev/*"
      - "feature/*"

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      outputA: "hello"
      outputB: "goodbye"

    steps:
      - name: print
        run: echo "Hello World"
