name: Empty

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches:
      - master
      - 'dev/*'
      - 'feature/*'

env:
  description: This workflow is used to test the GitHub Actions API. It does not do anything useful, but it can be triggered quickly because it has not inputs.

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      outputA: 'hello'
      outputB: 'goodbye'

    steps:
      - name: print
        run: echo "Hello World"
