name: Fail

on: 
  workflow_dispatch:

env:
  description: This is an testing template used to what happens when a template fails. This template will always fail.

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      outputA: 'hello'
      outputB: 'goodbye'

    steps:
      - run: echo "Hello World"
      - run: exit 1
        
