name: Gen AI Gateway

on:
  workflow_dispatch:

env:
  description: This workflow is used to enable the Gen AI Gateway for an intelligetn application. It will update the application AI endpoint to flow traffic through the Gen AI Gateway, enabling load balancing, token usage metrics, and 

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      outputA: 'hello'
      outputB: 'goodbye'

    steps:
      - name: print
        run: echo "The Gen AI Gateway is now enabled for this application."
