name: Enable OpenAI Load Balancing

on:
  workflow_dispatch:
    inputs:
      opena_loadbalancing_backend:
        description: Select the desired load balancing backend 
        type: choice
        options: 
          - "Multi-region North America" 
          - "Single-region North America"
          - "Global"
        required: true
        default: "Multi-region North America"

env:
  description: This workflow will add additional OpenAI capacity to your application. It will update your OpenAI endpoint to an approved backend configured by the Contoso OpenAI team. 
jobs:
  enable_openai_loadbalancing:
    runs-on: ubuntu-latest
    outputs:
      outputA: 'hello'
      outputB: 'goodbye'
    steps:
      - name: enable_load_balancing
        run: echo "Added load balancing"
      - name: finished  
        run: echo "Successful application of load balancing"
  notify_team:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      outputA: 'hello'
      outputB: 'goodbye'

    steps:
      - run: echo "### Hello Team! :rocket:" >> $GITHUB_STEP_SUMMARY
      - name: Notify Team
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.PLATYWEBHOOKURL }}
          title: Message from Contoso Platform Engineering Team
          summary: OpenAI Load Balancing
          text: "Hi team, your application has had the Multi-region North America load balancing backend applied." 
          sections: '[{ "activityTitle": "Load Balacing Policy Applied" },{"activityImage":"https://logos-world.net/wp-content/uploads/2023/10/Microsoft-Copilot-Logo-500x281.png"},{ "activitySubtitle":"${{inputs.openai_loadbalancing_backend}}" },{ "activityText":"Successfully applied the load balacing backend." }]'
          actions: '[{ "@type": "OpenUri", "name": "GoTo Repo", "targets": [{ "os": "default", "uri": "https://github.com/microsoft/developer-platform" }]}]'
