name: Entity Inputs

on:
  workflow_dispatch:
    inputs:
      ref_repo:
        description: Select a repository
        type: string
        required: true
      ref_environment:
        description: Select an environment
        type: string
        required: false

env:
  description: This workflow is used to test entity inputs that resolve to entity references.

jobs:
  talk:
    environment: ${{ inputs.ref_environment }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "### Repository ${{ inputs.ref_repository }}! :rocket:" >> $GITHUB_STEP_SUMMARY
      - run: echo "### Environment ${{ inputs.ref_environment }}! :rocket:" >> $GITHUB_STEP_SUMMARY
