name: Entity Inputs

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Select a repository
        type: string
        required: true
      environment_picker:
        description: Select an environment
        type: choice
        required: false
        options:
          - dev
          - test
          - staging
          - production

env:
  description: This workflow is used to test entity inputs that resolve to entity references.

jobs:
  talk:
    runs-on: ubuntu-latest

    steps:
      - run: echo "### Repository ${{ inputs.repository }}! :rocket:" >> $GITHUB_STEP_SUMMARY
      - run: echo "### Environment ${{ inputs.environment_picker }}! :rocket:" >> $GITHUB_STEP_SUMMARY
